sudo: required
language: csharp
mono: none
dotnet: 2.0.0
services:
  - docker
script:
  - docker build -t damonf8086/dotnetcore-ci:$TAG .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push damonf8086/dotnetcore-ci:$TAG
env:
  global:
    - secure: qcKCgn7AOONXtcdH1wDMzahpppmteEOThCSmXjl/jhyMNVGngRG+dWlZEs68QtOsZI6Abld69eThXrutr+YxK7XC0myzko/bCQcq3JpHYb1Ci1WbwGHJkzd9IPySflEaNCtreqhJPbGWEzd+JIczaTJH6reN8/lZrj9maqSRWk29LQMIMvITz8DXyey2vnMXn1rGABNulbZ+nygfjZou76nbUXh/VNPmJxWrXqMf/ENXtmH2msNKD4irMUiZSoXB21593Vrdk+jLt/M5rOu9ZkS4a1G3GX0cHgGXjSeLinqY3bm81Rp548C9p6UjwoZ4OSG52NO4VAOBTaYSFusDDVn7edAkhfOBwpNJhm5v2+lEFjMKzEOUe5O5fvZnI10axMxJaDykKCAwYunJw+/rY2mlQ6PBmvCg5O1YtmcFeBjCN5aZ4pv5o9e9iZs6MfZ7vE2/vSBohVBLUO/TJIcAIAe1StO24XhPn2eTje1W0v6Wn7lKYG2au3a+DXh7VvPQmeJ5qr+0sPnXYN7dKL4gMgNd/RCO02GdCgbxhtqHNQgocPcruezpZ79p5UVN/1FW4XV6r3q2JkCZXMumGpRv4XeF+oxwF9TmqhC31t/Uac/4Y6v9Ei1gc88do7rBjz7w1fvRcKWd7Rmdjxxf6hpuLRzK3tmjbg8tO29QE6lwT+I=
    - secure: Hf5pdtysoOPg+K7uiumLGDErQZuZPWsvecmsnwUqnXsUYLBB0GIwUaJmd8VFkgEDjIW9zC/pplGXdZPwI/l+L9sct6V1BlCoK8CG1YJKAH+G1OABlgQJse9mbgV6rpbWhweiML0vwKjSWbI2eKvLpoxipXj3m1wuDlOANJBojo9/7liBEKMj0i82pYDkDYG/T2PGPR3fy1XEro3Utg8yj8JrrX7asx3dIQEO1MN03mXCki+XGZOWeaSpnpLjVfaxIOaXjMpYYxZBbVJWBNolAkk65btMKtB02//D5rTqSCchNicVCCZSCxyrwUHj4lI6Gifd8AKbyZb3h4Oong2MrBaEANTQnHBXdNR5o656S3DvqTsHck55zGHGobGXX0WRksYdPpN5lNXRGZVseV2h5NQmSP/cu+C30y25AB33Oy3MbEE3WVNtkiQVKwmryLvOJqVZcIvrHRe1mS0J3RNE6rEZMP+G7+3+rpKj1QkGi+qUbqLSGAVETiYmLj10AivVMnvN5UEF0lmeG7h+SXohqnuNUBkKgblSfmyJzK1IFG3xyxISHGRlZtODjiNEX0zGJTduTlEEZLU8/eWKWlFh0blke1BZIj8hUJfBczYa73xQsWKNrJ5XXegM0eJFiyPulaVxStM3cHp3xNQvIyhd4EWdGYCd4UNUF3tjR1RpAy8=
    - TAG=Travis-0.1.$TRAVIS_BUILD_NUMBER
