version: 2
jobs:
  build:
    # docker is the "executor type"
    docker:
      # This is the "Primary container", for our purposes we just need it to have docker installed.
      # Its best practice to explicitly set the tag version.
      - image: docker:18.02.0-ce
    working_directory: /app
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout

      # setup_remote_docker is required to create docker images for deployment
      # Creates a remote environment, and the primary container is configured to use it.
      # Docker related commands will be executed in the new environment.
      - setup_remote_docker:
          version: 17.05.0-ce
          docker_layer_caching: true

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image 
      # DOCKER_USER & DOCKER_PASS are environment variables setup in the CirlceCi project website
      - run: |
          TAG=Circle-0.1.$CIRCLE_BUILD_NUM
          docker build -t damonf8086/dotnetcore-ci:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push damonf8086/dotnetcore-ci:$TAG